name: Go Build and Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22  # Use the Go version of your project

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go mod tidy

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: some setup config here
          version: latest
          args: --enable=vet --enable=staticcheck

      - name: Vet
        run: go vet ./...

      - name: Staticcheck
        run: staticcheck ./...

      - name: Build
        run: go build ./...
